# Generated by Django 4.0.5 on 2022-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name_plural': 'tweets'},
        ),
        migrations.AddField(
            model_name='tweets',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
