# Generated by Django 4.0.5 on 2022-06-18 10:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0002_alter_tweets_options_tweets_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
