# Generated by Django 4.0.5 on 2022-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0004_alter_tweets_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('5 minute', 5), ('10 minute', 10), ('15 minute', 15), ('25 minute', 25), ('30 minute', 30), ('shuffle', 'shuffle')], max_length=50)),
                ('schedule_till', models.CharField(choices=[('1 month', 30), ('3 month', 90), ('6 month', 180), ('1 year', 365)], max_length=50)),
            ],
        ),
    ]
