# Generated by Django 4.0.5 on 2022-06-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0005_conf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conf',
            new_name='Configr',
        ),
        migrations.AlterModelOptions(
            name='configr',
            options={'verbose_name_plural': 'bot configuration'},
        ),
    ]
