# Generated by Django 4.0.5 on 2022-06-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0006_rename_conf_configr_alter_configr_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configr',
            name='duration',
            field=models.CharField(choices=[(5, '5 minute'), (10, '10 minute'), (15, '15 minute'), (25, '25 minute'), (30, '30 minute'), ('shuffle', 'shuffle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='configr',
            name='schedule_till',
            field=models.CharField(choices=[(30, '1 month'), (90, '3 month'), (180, '6 month'), (365, '1 year')], max_length=50),
        ),
    ]
