# Generated by Django 4.0.5 on 2022-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0008_alter_configr_duration_alter_configr_schedule_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configr',
            name='duration',
            field=models.IntegerField(choices=[(5, '5 minute'), (10, '10 minute'), (15, '15 minute'), (25, '25 minute'), (30, '30 minute'), ('shuffle', 'shuffle')], verbose_name='Interval between tweets'),
        ),
        migrations.AlterField(
            model_name='configr',
            name='schedule_till',
            field=models.IntegerField(choices=[(30, '1 month'), (90, '3 month'), (180, '6 month'), (365, '1 year')]),
        ),
    ]
