# Generated by Django 4.0.5 on 2022-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0009_alter_configr_duration_alter_configr_schedule_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=300),
        ),
    ]
