# Generated by Django 4.0.5 on 2022-06-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0010_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
