# Generated by Django 4.0.5 on 2022-06-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0011_alter_tweets_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='images',
            new_name='img',
        ),
    ]
