# Generated by Django 4.0.5 on 2022-06-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0012_rename_images_tweets_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
