# Generated by Django 4.0.5 on 2022-06-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0014_alter_tweets_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
