# Generated by Django 4.0.5 on 2022-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0015_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configr',
            name='duration',
            field=models.IntegerField(choices=[(5, '5 minute'), (10, '10 minute'), (15, '15 minute'), (25, '25 minute'), (30, '30 minute')], verbose_name='Interval between tweets'),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
