# Generated by Django 4.0.5 on 2022-06-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0016_alter_configr_duration_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
