# Generated by Django 4.0.5 on 2022-06-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0017_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='configr',
            name='add_current_date',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='configr',
            name='add_quotes',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='configr',
            name='add_random_emoji',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Add random emoji'),
        ),
        migrations.AddField(
            model_name='configr',
            name='add_random_number',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='configr',
            name='no_of_emoji',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
