# Generated by Django 4.0.5 on 2022-06-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0018_configr_add_current_date_configr_add_quotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
