# Generated by Django 4.0.5 on 2022-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0021_alter_tweets_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
