# Generated by Django 4.0.5 on 2022-07-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate', '0024_alter_tweets_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True, max_length=300, null=True, unique=True)),
            ],
        ),
    ]
